name: Build GDJ Installer

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pywin32 packaging requests

      - name: Build GDJ.exe with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name=GDJ main.py

      - name: Install Inno Setup
        run: |
          curl -L -o InnoSetup.exe https://jrsoftware.org/is/InnoSetup-6.2.2.exe
          start /wait InnoSetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART

      - name: Build installer with Inno Setup
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\GDJ_Installer.iss

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: GDJ-Build
          path: |
            dist\GDJ.exe
            installer\Output\GDJ_Installer.exe
